GET http://localhost:3001/api/persons

###

DELETE http://localhost:3001/api/persons/5ee7788986c87d797079b696

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Astrid Lindgren",
  "number": "761-1243613"
}

###

GET http://localhost:3001/api/persons/5ee8be3d64889c3011713bae

###

GET http://localhost:3001/info